FROM registry.redhat.io/dotnet/dotnet-31-runtime-rhel7

COPY bin/ /var/Globo.Integration.Grids.AsRun.ApiGridTranslator.Service/
CMD ["dotnet", "/var/Globo.Integration.Grids.AsRun.ApiGridTranslator.Service/Globo.Integration.Grids.AsRun.ApiGridTranslator.Service.dll"]