//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.MigracaoSisComSoap")]
    public interface MigracaoSisComSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetMigracaoSisComRoteiro", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.SetMigracaoSisComRoteiroResponse> SetMigracaoSisComRoteiroAsync(ServiceReference1.SetMigracaoSisComRoteiroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetMigracaoGuia", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.SetMigracaoGuiaResponse> SetMigracaoGuiaAsync(ServiceReference1.SetMigracaoGuiaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterProgramacao", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.ObterProgramacaoResponse> ObterProgramacaoAsync(ServiceReference1.ObterProgramacaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetMigracaoIBMS", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.SetMigracaoIBMSResponse> SetMigracaoIBMSAsync(ServiceReference1.SetMigracaoIBMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtemRoteiroPosExibicaoPebble", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.ObtemRoteiroPosExibicaoPebbleResponse> ObtemRoteiroPosExibicaoPebbleAsync(ServiceReference1.ObtemRoteiroPosExibicaoPebbleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtemRoteiroPosExibicaoHarris", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.ObtemRoteiroPosExibicaoHarrisResponse> ObtemRoteiroPosExibicaoHarrisAsync(ServiceReference1.ObtemRoteiroPosExibicaoHarrisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtemRoteiroPosExibicaoOmneon", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.ObtemRoteiroPosExibicaoOmneonResponse> ObtemRoteiroPosExibicaoOmneonAsync(ServiceReference1.ObtemRoteiroPosExibicaoOmneonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterInfoProgramas", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.ObterInfoProgramasResponse> ObterInfoProgramasAsync(ServiceReference1.ObterInfoProgramasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetMigracaoSisComRoteiroRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetMigracaoSisComRoteiro", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.SetMigracaoSisComRoteiroRequestBody Body;
        
        public SetMigracaoSisComRoteiroRequest()
        {
        }
        
        public SetMigracaoSisComRoteiroRequest(ServiceReference1.SetMigracaoSisComRoteiroRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetMigracaoSisComRoteiroRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string emissora;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string database;
        
        public SetMigracaoSisComRoteiroRequestBody()
        {
        }
        
        public SetMigracaoSisComRoteiroRequestBody(string xml, string emissora, string database)
        {
            this.xml = xml;
            this.emissora = emissora;
            this.database = database;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetMigracaoSisComRoteiroResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetMigracaoSisComRoteiroResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.SetMigracaoSisComRoteiroResponseBody Body;
        
        public SetMigracaoSisComRoteiroResponse()
        {
        }
        
        public SetMigracaoSisComRoteiroResponse(ServiceReference1.SetMigracaoSisComRoteiroResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetMigracaoSisComRoteiroResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SetMigracaoSisComRoteiroResult;
        
        public SetMigracaoSisComRoteiroResponseBody()
        {
        }
        
        public SetMigracaoSisComRoteiroResponseBody(string SetMigracaoSisComRoteiroResult)
        {
            this.SetMigracaoSisComRoteiroResult = SetMigracaoSisComRoteiroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetMigracaoGuiaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetMigracaoGuia", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.SetMigracaoGuiaRequestBody Body;
        
        public SetMigracaoGuiaRequest()
        {
        }
        
        public SetMigracaoGuiaRequest(ServiceReference1.SetMigracaoGuiaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetMigracaoGuiaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string emissora;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string database;
        
        public SetMigracaoGuiaRequestBody()
        {
        }
        
        public SetMigracaoGuiaRequestBody(string xml, string emissora, string database)
        {
            this.xml = xml;
            this.emissora = emissora;
            this.database = database;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetMigracaoGuiaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetMigracaoGuiaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.SetMigracaoGuiaResponseBody Body;
        
        public SetMigracaoGuiaResponse()
        {
        }
        
        public SetMigracaoGuiaResponse(ServiceReference1.SetMigracaoGuiaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetMigracaoGuiaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SetMigracaoGuiaResult;
        
        public SetMigracaoGuiaResponseBody()
        {
        }
        
        public SetMigracaoGuiaResponseBody(string SetMigracaoGuiaResult)
        {
            this.SetMigracaoGuiaResult = SetMigracaoGuiaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterProgramacaoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterProgramacao", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ObterProgramacaoRequestBody Body;
        
        public ObterProgramacaoRequest()
        {
        }
        
        public ObterProgramacaoRequest(ServiceReference1.ObterProgramacaoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObterProgramacaoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DataInicio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DataFim;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Emissoras;
        
        public ObterProgramacaoRequestBody()
        {
        }
        
        public ObterProgramacaoRequestBody(string DataInicio, string DataFim, string Emissoras)
        {
            this.DataInicio = DataInicio;
            this.DataFim = DataFim;
            this.Emissoras = Emissoras;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterProgramacaoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterProgramacaoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ObterProgramacaoResponseBody Body;
        
        public ObterProgramacaoResponse()
        {
        }
        
        public ObterProgramacaoResponse(ServiceReference1.ObterProgramacaoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObterProgramacaoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObterProgramacaoResult;
        
        public ObterProgramacaoResponseBody()
        {
        }
        
        public ObterProgramacaoResponseBody(string ObterProgramacaoResult)
        {
            this.ObterProgramacaoResult = ObterProgramacaoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetMigracaoIBMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetMigracaoIBMS", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.SetMigracaoIBMSRequestBody Body;
        
        public SetMigracaoIBMSRequest()
        {
        }
        
        public SetMigracaoIBMSRequest(ServiceReference1.SetMigracaoIBMSRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetMigracaoIBMSRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string emissora;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string database;
        
        public SetMigracaoIBMSRequestBody()
        {
        }
        
        public SetMigracaoIBMSRequestBody(string xml, string emissora, string database)
        {
            this.xml = xml;
            this.emissora = emissora;
            this.database = database;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetMigracaoIBMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetMigracaoIBMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.SetMigracaoIBMSResponseBody Body;
        
        public SetMigracaoIBMSResponse()
        {
        }
        
        public SetMigracaoIBMSResponse(ServiceReference1.SetMigracaoIBMSResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetMigracaoIBMSResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SetMigracaoIBMSResult;
        
        public SetMigracaoIBMSResponseBody()
        {
        }
        
        public SetMigracaoIBMSResponseBody(string SetMigracaoIBMSResult)
        {
            this.SetMigracaoIBMSResult = SetMigracaoIBMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtemRoteiroPosExibicaoPebbleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtemRoteiroPosExibicaoPebble", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ObtemRoteiroPosExibicaoPebbleRequestBody Body;
        
        public ObtemRoteiroPosExibicaoPebbleRequest()
        {
        }
        
        public ObtemRoteiroPosExibicaoPebbleRequest(ServiceReference1.ObtemRoteiroPosExibicaoPebbleRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtemRoteiroPosExibicaoPebbleRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string emissora;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string database;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string xmlAsRunAutomacao;
        
        public ObtemRoteiroPosExibicaoPebbleRequestBody()
        {
        }
        
        public ObtemRoteiroPosExibicaoPebbleRequestBody(string emissora, string database, string xmlAsRunAutomacao)
        {
            this.emissora = emissora;
            this.database = database;
            this.xmlAsRunAutomacao = xmlAsRunAutomacao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtemRoteiroPosExibicaoPebbleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtemRoteiroPosExibicaoPebbleResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ObtemRoteiroPosExibicaoPebbleResponseBody Body;
        
        public ObtemRoteiroPosExibicaoPebbleResponse()
        {
        }
        
        public ObtemRoteiroPosExibicaoPebbleResponse(ServiceReference1.ObtemRoteiroPosExibicaoPebbleResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtemRoteiroPosExibicaoPebbleResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtemRoteiroPosExibicaoPebbleResult;
        
        public ObtemRoteiroPosExibicaoPebbleResponseBody()
        {
        }
        
        public ObtemRoteiroPosExibicaoPebbleResponseBody(string ObtemRoteiroPosExibicaoPebbleResult)
        {
            this.ObtemRoteiroPosExibicaoPebbleResult = ObtemRoteiroPosExibicaoPebbleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtemRoteiroPosExibicaoHarrisRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtemRoteiroPosExibicaoHarris", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ObtemRoteiroPosExibicaoHarrisRequestBody Body;
        
        public ObtemRoteiroPosExibicaoHarrisRequest()
        {
        }
        
        public ObtemRoteiroPosExibicaoHarrisRequest(ServiceReference1.ObtemRoteiroPosExibicaoHarrisRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtemRoteiroPosExibicaoHarrisRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string emissora;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string database;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string titulo;
        
        public ObtemRoteiroPosExibicaoHarrisRequestBody()
        {
        }
        
        public ObtemRoteiroPosExibicaoHarrisRequestBody(string emissora, string database, string titulo)
        {
            this.emissora = emissora;
            this.database = database;
            this.titulo = titulo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtemRoteiroPosExibicaoHarrisResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtemRoteiroPosExibicaoHarrisResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ObtemRoteiroPosExibicaoHarrisResponseBody Body;
        
        public ObtemRoteiroPosExibicaoHarrisResponse()
        {
        }
        
        public ObtemRoteiroPosExibicaoHarrisResponse(ServiceReference1.ObtemRoteiroPosExibicaoHarrisResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtemRoteiroPosExibicaoHarrisResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtemRoteiroPosExibicaoHarrisResult;
        
        public ObtemRoteiroPosExibicaoHarrisResponseBody()
        {
        }
        
        public ObtemRoteiroPosExibicaoHarrisResponseBody(string ObtemRoteiroPosExibicaoHarrisResult)
        {
            this.ObtemRoteiroPosExibicaoHarrisResult = ObtemRoteiroPosExibicaoHarrisResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtemRoteiroPosExibicaoOmneonRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtemRoteiroPosExibicaoOmneon", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ObtemRoteiroPosExibicaoOmneonRequestBody Body;
        
        public ObtemRoteiroPosExibicaoOmneonRequest()
        {
        }
        
        public ObtemRoteiroPosExibicaoOmneonRequest(ServiceReference1.ObtemRoteiroPosExibicaoOmneonRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtemRoteiroPosExibicaoOmneonRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string emissora;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string database;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string titulo;
        
        public ObtemRoteiroPosExibicaoOmneonRequestBody()
        {
        }
        
        public ObtemRoteiroPosExibicaoOmneonRequestBody(string emissora, string database, string titulo)
        {
            this.emissora = emissora;
            this.database = database;
            this.titulo = titulo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtemRoteiroPosExibicaoOmneonResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtemRoteiroPosExibicaoOmneonResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ObtemRoteiroPosExibicaoOmneonResponseBody Body;
        
        public ObtemRoteiroPosExibicaoOmneonResponse()
        {
        }
        
        public ObtemRoteiroPosExibicaoOmneonResponse(ServiceReference1.ObtemRoteiroPosExibicaoOmneonResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtemRoteiroPosExibicaoOmneonResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtemRoteiroPosExibicaoOmneonResult;
        
        public ObtemRoteiroPosExibicaoOmneonResponseBody()
        {
        }
        
        public ObtemRoteiroPosExibicaoOmneonResponseBody(string ObtemRoteiroPosExibicaoOmneonResult)
        {
            this.ObtemRoteiroPosExibicaoOmneonResult = ObtemRoteiroPosExibicaoOmneonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterInfoProgramasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterInfoProgramas", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ObterInfoProgramasRequestBody Body;
        
        public ObterInfoProgramasRequest()
        {
        }
        
        public ObterInfoProgramasRequest(ServiceReference1.ObterInfoProgramasRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObterInfoProgramasRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string emissora;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string reconid;
        
        public ObterInfoProgramasRequestBody()
        {
        }
        
        public ObterInfoProgramasRequestBody(string emissora, string reconid)
        {
            this.emissora = emissora;
            this.reconid = reconid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterInfoProgramasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterInfoProgramasResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ObterInfoProgramasResponseBody Body;
        
        public ObterInfoProgramasResponse()
        {
        }
        
        public ObterInfoProgramasResponse(ServiceReference1.ObterInfoProgramasResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObterInfoProgramasResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObterInfoProgramasResult;
        
        public ObterInfoProgramasResponseBody()
        {
        }
        
        public ObterInfoProgramasResponseBody(string ObterInfoProgramasResult)
        {
            this.ObterInfoProgramasResult = ObterInfoProgramasResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface MigracaoSisComSoapChannel : ServiceReference1.MigracaoSisComSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class MigracaoSisComSoapClient : System.ServiceModel.ClientBase<ServiceReference1.MigracaoSisComSoap>, ServiceReference1.MigracaoSisComSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MigracaoSisComSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(MigracaoSisComSoapClient.GetBindingForEndpoint(endpointConfiguration), MigracaoSisComSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MigracaoSisComSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MigracaoSisComSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MigracaoSisComSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MigracaoSisComSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MigracaoSisComSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.SetMigracaoSisComRoteiroResponse> ServiceReference1.MigracaoSisComSoap.SetMigracaoSisComRoteiroAsync(ServiceReference1.SetMigracaoSisComRoteiroRequest request)
        {
            return base.Channel.SetMigracaoSisComRoteiroAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.SetMigracaoSisComRoteiroResponse> SetMigracaoSisComRoteiroAsync(string xml, string emissora, string database)
        {
            ServiceReference1.SetMigracaoSisComRoteiroRequest inValue = new ServiceReference1.SetMigracaoSisComRoteiroRequest();
            inValue.Body = new ServiceReference1.SetMigracaoSisComRoteiroRequestBody();
            inValue.Body.xml = xml;
            inValue.Body.emissora = emissora;
            inValue.Body.database = database;
            return ((ServiceReference1.MigracaoSisComSoap)(this)).SetMigracaoSisComRoteiroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.SetMigracaoGuiaResponse> ServiceReference1.MigracaoSisComSoap.SetMigracaoGuiaAsync(ServiceReference1.SetMigracaoGuiaRequest request)
        {
            return base.Channel.SetMigracaoGuiaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.SetMigracaoGuiaResponse> SetMigracaoGuiaAsync(string xml, string emissora, string database)
        {
            ServiceReference1.SetMigracaoGuiaRequest inValue = new ServiceReference1.SetMigracaoGuiaRequest();
            inValue.Body = new ServiceReference1.SetMigracaoGuiaRequestBody();
            inValue.Body.xml = xml;
            inValue.Body.emissora = emissora;
            inValue.Body.database = database;
            return ((ServiceReference1.MigracaoSisComSoap)(this)).SetMigracaoGuiaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.ObterProgramacaoResponse> ServiceReference1.MigracaoSisComSoap.ObterProgramacaoAsync(ServiceReference1.ObterProgramacaoRequest request)
        {
            return base.Channel.ObterProgramacaoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ObterProgramacaoResponse> ObterProgramacaoAsync(string DataInicio, string DataFim, string Emissoras)
        {
            ServiceReference1.ObterProgramacaoRequest inValue = new ServiceReference1.ObterProgramacaoRequest();
            inValue.Body = new ServiceReference1.ObterProgramacaoRequestBody();
            inValue.Body.DataInicio = DataInicio;
            inValue.Body.DataFim = DataFim;
            inValue.Body.Emissoras = Emissoras;
            return ((ServiceReference1.MigracaoSisComSoap)(this)).ObterProgramacaoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.SetMigracaoIBMSResponse> ServiceReference1.MigracaoSisComSoap.SetMigracaoIBMSAsync(ServiceReference1.SetMigracaoIBMSRequest request)
        {
            return base.Channel.SetMigracaoIBMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.SetMigracaoIBMSResponse> SetMigracaoIBMSAsync(string xml, string emissora, string database)
        {
            ServiceReference1.SetMigracaoIBMSRequest inValue = new ServiceReference1.SetMigracaoIBMSRequest();
            inValue.Body = new ServiceReference1.SetMigracaoIBMSRequestBody();
            inValue.Body.xml = xml;
            inValue.Body.emissora = emissora;
            inValue.Body.database = database;
            return ((ServiceReference1.MigracaoSisComSoap)(this)).SetMigracaoIBMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.ObtemRoteiroPosExibicaoPebbleResponse> ServiceReference1.MigracaoSisComSoap.ObtemRoteiroPosExibicaoPebbleAsync(ServiceReference1.ObtemRoteiroPosExibicaoPebbleRequest request)
        {
            return base.Channel.ObtemRoteiroPosExibicaoPebbleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ObtemRoteiroPosExibicaoPebbleResponse> ObtemRoteiroPosExibicaoPebbleAsync(string emissora, string database, string xmlAsRunAutomacao)
        {
            ServiceReference1.ObtemRoteiroPosExibicaoPebbleRequest inValue = new ServiceReference1.ObtemRoteiroPosExibicaoPebbleRequest();
            inValue.Body = new ServiceReference1.ObtemRoteiroPosExibicaoPebbleRequestBody();
            inValue.Body.emissora = emissora;
            inValue.Body.database = database;
            inValue.Body.xmlAsRunAutomacao = xmlAsRunAutomacao;
            return ((ServiceReference1.MigracaoSisComSoap)(this)).ObtemRoteiroPosExibicaoPebbleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.ObtemRoteiroPosExibicaoHarrisResponse> ServiceReference1.MigracaoSisComSoap.ObtemRoteiroPosExibicaoHarrisAsync(ServiceReference1.ObtemRoteiroPosExibicaoHarrisRequest request)
        {
            return base.Channel.ObtemRoteiroPosExibicaoHarrisAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ObtemRoteiroPosExibicaoHarrisResponse> ObtemRoteiroPosExibicaoHarrisAsync(string emissora, string database, string titulo)
        {
            ServiceReference1.ObtemRoteiroPosExibicaoHarrisRequest inValue = new ServiceReference1.ObtemRoteiroPosExibicaoHarrisRequest();
            inValue.Body = new ServiceReference1.ObtemRoteiroPosExibicaoHarrisRequestBody();
            inValue.Body.emissora = emissora;
            inValue.Body.database = database;
            inValue.Body.titulo = titulo;
            return ((ServiceReference1.MigracaoSisComSoap)(this)).ObtemRoteiroPosExibicaoHarrisAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.ObtemRoteiroPosExibicaoOmneonResponse> ServiceReference1.MigracaoSisComSoap.ObtemRoteiroPosExibicaoOmneonAsync(ServiceReference1.ObtemRoteiroPosExibicaoOmneonRequest request)
        {
            return base.Channel.ObtemRoteiroPosExibicaoOmneonAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ObtemRoteiroPosExibicaoOmneonResponse> ObtemRoteiroPosExibicaoOmneonAsync(string emissora, string database, string titulo)
        {
            ServiceReference1.ObtemRoteiroPosExibicaoOmneonRequest inValue = new ServiceReference1.ObtemRoteiroPosExibicaoOmneonRequest();
            inValue.Body = new ServiceReference1.ObtemRoteiroPosExibicaoOmneonRequestBody();
            inValue.Body.emissora = emissora;
            inValue.Body.database = database;
            inValue.Body.titulo = titulo;
            return ((ServiceReference1.MigracaoSisComSoap)(this)).ObtemRoteiroPosExibicaoOmneonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.ObterInfoProgramasResponse> ServiceReference1.MigracaoSisComSoap.ObterInfoProgramasAsync(ServiceReference1.ObterInfoProgramasRequest request)
        {
            return base.Channel.ObterInfoProgramasAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ObterInfoProgramasResponse> ObterInfoProgramasAsync(string emissora, string reconid)
        {
            ServiceReference1.ObterInfoProgramasRequest inValue = new ServiceReference1.ObterInfoProgramasRequest();
            inValue.Body = new ServiceReference1.ObterInfoProgramasRequestBody();
            inValue.Body.emissora = emissora;
            inValue.Body.reconid = reconid;
            return ((ServiceReference1.MigracaoSisComSoap)(this)).ObterInfoProgramasAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MigracaoSisComSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.MigracaoSisComSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MigracaoSisComSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/migracaosiscom/migracaosiscom.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.MigracaoSisComSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/migracaosiscom/migracaosiscom.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            MigracaoSisComSoap,
            
            MigracaoSisComSoap12,
        }
    }
}
